In [69]:
import numpy as np

In [73]:
a = np.arange(0,21,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [75]:
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
a[0:21:3]

array([ 0,  3,  6,  9, 12, 15, 18])